name: CI

#We can specify whcih Github events will trigger a CI build
on: push

#now define a single job 'build' (but could define more)
jobs:

    build:

        #we can also specify the OS to run tests on
        runs-on: ubuntu-latest

        #a job is a sequence of steps
        steps:

        # Next we need to checout out repository, and set up in Python
        # A 'name' is just an optional label shown in the log - helpful to clarify progress - and can be anything
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"
            
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

        - name: Test with PyTest
          run: |
            python -m pytest --cov=inflammation.models tests/test_models.py